### ISSUE TITLE
Linter loops over file 7 times?

### ISSUE THREAD

**Issue by mgoggin** [Shopify/erb-lint#103]
Hi there.

I was reviewing the source for this gem and found something I was curious about.

https://github.com/Shopify/erb-lint/blob/b0d8579277e756ed26aaccf13581f75d9a5e0b9e/lib/erb_lint/cli.rb#L103-L120

Why does the linter loop over autocorrectable files 7 times? Is 7 an arbitrary number?

I saw that it was added in bd096a1f for #36.

On the face of it, it looks like we'd just be wasting CPU cycles by performing the same operation an arbitrary number of times.

Any clues as to why this was the approach that was taken would be greatly appreciated. Thanks!

**Comment by EiNSTeiN-** [comment]
the correction loop stops once no more correction can be applied, so rest assured we're not wasting cpu cycles. 

we always have to check if more corrections can be applied because one linter may apply corrections that introduce more violations. for example one linter may concern itself with adding a newline somewhere, and another may add the proper indentation to the newly broken up line. If the first linter concerned itself with indentation as well as breaking up the line, it would be a duplication of concerns that might make linters more difficult to test and maintain. rubocop works the same way, this autocorrect code is largely modeled after theirs.

**Comment by mgoggin** [comment]
Sounds good to me. Thanks for the reply!
