### ISSUE TITLE
Possibility to turn erb-lint into rubocop extension?

### ISSUE THREAD

**Issue by aried3r** [Shopify/erb-lint#152]
See [this](https://docs.rubocop.org/en/stable/extensions/). There's a few extensions, mostly focusing on Ruby code.

I didn't dig into the code of erb-lint deep enough to be able to tell if this project has to stay separate from rubocop or if it could be written as an extension? As an extension, it could theoretically also be adopted by rubocop-hq, much like rubocop-rspec was.

WDYT?

**Comment by rafaelfranca** [comment]
Right now Rubocop extensions don't allow us to plug new parsers. It only allow us to plug new cops and formatters. To be able to build erb-lint as an extension Rubocop should be able to parse ERB and it is not. I'm open for collaboration to make that happen but I'm not willing to make the effort to implement it since the way it is right now is good enough for our needs.

Closing this issue just to keep out issue lists low. Thank you for the suggestion.
