### ISSUE TITLE
Ignore strings in mustache templates

### ISSUE THREAD

**Issue by awead** [Shopify/erb-lint#186]
If the `HardCodedString` linter is enabled, mustache variables get flagged:

``` html
<template>
  <p>{{first_name}}</p>
</template>
```

I don't know what the best solution would be. Maybe ignore anything with `{{ }}`? I like using erb-lint a lot and could find some time to address this.

**Comment by rafaelfranca** [comment]
Maybe we should ignore the `template` tag all together? But that would mean hard coded strings in the template that ware not mustache variables would be ignored. I don't think erb lint should have knowledge about mustache because that is just inviting every single template language support and I don't want to support them.

I think it is better to you mark which string should not be checked using some kind of disable comment like `# erblint:disable HardCodedString`. This will need to be implemented of course.

PRs welcome but we will not implement it since we don't use mustache.

Closing since we will not work on it but feel free to open a PR with the disable feature. Thank you.
